version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      minor-dependencies:
        update-types:
          - "minor"
          - "patch"
