linters:
  disable-all: true
  enable:
    - errcheck
    - gocritic
    - govet
    - nonamedreturns
    - staticcheck
    - revive
  presets:
    - unused

linters-settings:
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: false
        arguments:
          - ["ID"] # Ignore
  staticcheck:
    checks:
      - '-SA3000'
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    enabled-checks:
      - ioutilDeprecated
    disabled-checks:
      - appendCombine
      - appendAssign
      - commentFormatting
      - ifElseChain
      - singleCaseSwitch

run:
  timeout: 3m
