linters:
  disable-all: true
  enable:
    - errcheck
    - gocritic
    - govet
    - nonamedreturns
    - staticcheck
  presets:
    - unused

linters-settings:
  staticcheck:
    checks:
      - '-SA3000'
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    enabled-checks:
      - ioutilDeprecated
    disabled-checks:
      - appendCombine
      - appendAssign
      - commentFormatting
      - ifElseChain
      - singleCaseSwitch

args: --timeout=3m
