name: Nightly E2E testing

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  e2e:
    name: E2E / Behavior tests
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
      fail-fast: false # We care about results from other pipelines

    steps:
      - uses: actions/checkout@v3

      - name: Setup VM for cifuzz
        uses: ./.github/actions/vm_setup
        with:
          os: ${{ matrix.os }}

      - name: Install cifuzz
        run: make install

      - name: Run e2e tests matrix
        run: go test ./e2e-tests/...
        env:
          E2E_TESTS_MATRIX: 1
