name: Release Pipeline

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  version:
    name: Get version number from tag
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.vars.outputs.version }}
    steps:
      - name: Read version
        id: vars
        # extract tag name without v prefix
        run: |
          TAG=${{ github.event.release.tag_name }}
          echo "version=${TAG#v}" >> $GITHUB_OUTPUT
        shell: bash

  tag_container_image:
    name: Tag container image
    needs: [version]
    uses: ./.github/workflows/workflow_container_image.yml
    with:
      version: ${{ needs.version.outputs.version }}
