name: Update docker default image

on:
  schedule:
    - cron: "0 7 * * 1"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ubuntu based image
        uses: docker/build-push-action@v5
        with:
          context: docker/cifuzz-ubuntu
          push: true
          tags: cifuzz/cifuzz-ubuntu:latest
