name: Sync releases to download portal

on:
  release:
    types:
      - edited
      - published
      - released

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VERSION_TAG: ${{ github.event.release.tag_name }}
jobs:
  upload:
    name: Sync Download Portal
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: robinraju/release-downloader@v1.8
        name: Download installer from release
        with:
          tag: ${{ env.VERSION_TAG }}
          fileName: "cifuzz_installer_*"
          out-file-path: installer

      - uses: LanceMcCarthy/Action-AzureBlobUpload@v2
        name: Uploading installer to azure blob storage
        with:
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          container_name: ${{ vars.AZURE_STORAGE_CONTAINER }}
          destination_folder: releases/${{ env.VERSION_TAG }}
          source_folder: installer
          delete_if_exists: true
          fail_if_source_empty: true
