name: Post Release Pipeline

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  version:
    name: Get version number from tag
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.vars.outputs.version }}
    steps:
      - name: Read version
        id: vars
        # extract tag name without v prefix
        run: |
          TAG=${{ github.event.release.tag_name }}
          echo "version=${TAG#v}" >> $GITHUB_OUTPUT
        shell: bash

  tag_container_image:
    name: Tag container image
    needs: [version]
    uses: ./.github/workflows/workflow_container_image.yml
    with:
      version: ${{ needs.version.outputs.version }}

  slack_notification:
    steps:
      - name: Send notification to slack release channel
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C03RCP31BML"
          # For posting a simple plain text message
          slack-message: ":tada: **cifuzz release ${{ github.event.release.tag_name }}**: {{ github.event.release.html_url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  send-release-event:
    runs-on: ubuntu-latest
    steps:
      - name: Send Release Event to datadog
        run: |
          curl -sX POST "https://api.datadoghq.eu/api/v1/events" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
            --data-raw '{
              "title": "cifuzz has been released",
              "text": "%%% \ncifuzz has been released with version **${{ github.event.release.tag_name }}**\n %%%",
              "tags": [
                "repo:${{ github.repository }}",
                "project:cifuzz",
                "version:${{ github.event.release.tag_name }}"
              ]
            }'
