name: PR Pipeline

on:
  merge_group:
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  # default values, as BASE_REF and HEAD_REF are only available
  # when triggered by a pull request
  BASE_REF: ${{ github.base_ref || 'main' }}
  HEAD_REF: ${{ github.head_ref ||  github.ref_name }}

jobs:
  no-wip-commits:
    name: No WIP or XXX commits
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Fetch the base branch
        run: git fetch origin "${BASE_REF}"

      - name: Check no commits starting with WIP
        run: |
          git fetch origin "${HEAD_REF}"
          git log "origin/${BASE_REF}..origin/${HEAD_REF}"
          if git log "origin/${BASE_REF}..origin/${HEAD_REF}" | grep -B4 -i -e "^\s\+WIP"; then
            exit 1
          fi

      - name: Check no commits starting with XXX
        run: |
          git fetch origin "${HEAD_REF}"
          if git log "origin/${BASE_REF}..origin/${HEAD_REF}" | grep -B4 -i -e "^\s\+XXX"; then
            exit 1
          fi

      - name: Check no commits starting with fixup
        run: |
          git fetch origin "${HEAD_REF}"
          if git log "origin/${BASE_REF}..origin/${HEAD_REF}" | grep -B4 -i -e "^\s\+fixup"; then
            exit 1
          fi
