# This Pipeline executes some kind of e2e test using the latest released installer to run cifuzz examples
# As it uses the installer created by the release pipeline it only runs after the
# release pipeline finished
name: E2E Installer Installation/Example Test

on:
  workflow_run:
    workflows: ["Release Pipeline"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-installer:
    name: ${{ matrix.os }} - test installer
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, ubuntu-22.04, windows-2022]
    steps:
      - uses: actions/checkout@v3

      - name: Setup VM for cifuzz
        uses: ./.github/actions/vm_setup
        with:
          repository_user: ${{ secrets.REPOSITORY_USER }}
          repository_token: ${{ secrets.REPOSITORY_TOKEN }}
          os: ${{ matrix.os }}

      - name: Download & execute latest installer
        run: sh -c "$(curl -fsSL https://downloads.code-intelligence.com/assets/install.sh)" ${{ secrets.DOWNLOAD_TOKEN }} latest
        # to make sure our install script is compatible to all the shells
        shell: sh

      - name: Test cifuzz
        run: cifuzz --version | grep -E "^cifuzz version [0-9]+.[0-9]+.[0-9]+$"
        shell: bash

      - name: Run cifuzz examples
        uses: ./.github/actions/run_cifuzz
        with:
          os: ${{ matrix.os }}
