# This name is used in other pipelines that run afterwards
# Be careful when changing it
name: Release Pipeline

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  version:
    name: Get version number from tag
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.vars.outputs.version }}
    steps:
      - name: Read version
        id: vars
        # extract tag name without v prefix
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        shell: bash

  installer:
    uses: ./.github/workflows/workflow_installer.yml
    needs: version
    permissions:
      actions: write # for uploading artifacts
    with:
      version: ${{ needs.version.outputs.version }}
      compatibility_check: ${{ vars.RELEASE_COMPATIBILITY_CHECK }}

  create_release:
    name: Create release
    runs-on: ubuntu-22.04
    needs: [version, installer]
    permissions:
      contents: write # for creating releases

    steps:
      # needed for the release template
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: cifuzz_installer

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: cifuzz Release ${{ needs.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: ./.github/release_template.md
          generate_release_notes: true
          files: cifuzz_installer_*
          fail_on_unmatched_files: true

  tag_container_image:
    name: Tag container image
    needs: [version, create_release]
    uses: ./.github/workflows/workflow_container_image.yml
    with:
      version: ${{ needs.version.outputs.version }}

  slack_notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: [version, create_release]
    steps:
      - name: Send notification to slack release channel
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C03RCP31BML"
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New CI Fuzz Release :tada:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Version*: ${{ needs.version.outputs.version }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Changelog & Downloads @ <https://github.com/CodeIntelligenceTesting/cifuzz/releases/tag/v${{ needs.version.outputs.version }}|GitHub>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  send-release-event:
    name: Datadog release tracking
    runs-on: ubuntu-latest
    needs: [version, create_release]
    steps:
      - name: Send Release Event to datadog
        run: |
          curl -sX POST "https://api.datadoghq.eu/api/v1/events" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
            --data-raw '{
              "title": "cifuzz has been released",
              "text": "%%% \ncifuzz has been released with version **${{ needs.version.outputs.version }}**\n %%%",
              "tags": [
                "repo:${{ github.repository }}",
                "project:cifuzz",
                "version:${{ needs.version.outputs.version }}"
              ]
            }'
