name: Release E2E testing

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  e2e:
    name: E2E / Behavior tests
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
      fail-fast: false # We care about results from other pipelines

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Install cifuzz
        run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/CodeIntelligenceTesting/cifuzz/main/install.sh)"
        shell: sh

      # "$HOME/cifuzz/bin" can be removed as soon as new install path is released
      - name: Update Path - MacOS/Linux
        if: contains(matrix.os, 'macos')
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        shell: bash

      - name: Update Path - Windows
        if: contains(matrix.os, 'windows')
        # Windows can't find cifuzz executable without this
        # https://www.scivision.dev/github-actions-path-append/
        run: |
          echo "${HOME}/AppData/Roaming/cifuzz/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Run e2e tests matrix
        run: go test ./e2e-tests/...
        env:
          E2E_TESTS_MATRIX: 1
