name: General Pipeline 

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'

jobs:
  linting:
    uses: CodeIntelligenceTesting/cifuzz/.github/workflows/resuable_linting.yml@main
  testing:
    uses: CodeIntelligenceTesting/cifuzz/.github/workflows/reusable_testing.yml@main
