# This Pipeline executes some kind of e2e test by running instructions from the docs
# To not unnecessarily lengthen the runtime of the PR pipelines we just run these
# tests after pushing to main.
#
# To test changes to this pipeline on a branch that's not main, trigger
# the workflow manually by selecting the workflow in the left sidebar
# in the "Actions" tab and clicking "Run workflow" on the right, then
# select the branch you want to test.

name: E2E Source Installation/Example Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # we are running the linux part in container as it is a more realistic starting
  # point than the preinstalled github VMs
  from_source_linux:
    name: ${{ matrix.container}} - install from source
    runs-on: ubuntu-22.04
    container:
      image: ${{ matrix.container}}
      options: --privileged
    strategy:
      matrix:
        container: ["ubuntu:22.04", "archlinux:latest"]
    steps:
      - name: Install dependencies with pacman
        if: contains(matrix.container, 'archlinux')
        # please make sure this is in sync with the README.md / installation docs
        # glibc was added as it is required by nodejs which is used to run
        # the github action "action/checkout"
        run: pacman -Sy --noconfirm git make cmake clang docker docker-buildx llvm lcov jdk17-openjdk maven gradle python

      - name: Build libcap statically
        if: contains(matrix.container, 'archlinux')
        run: |
          pacman -Syu --noconfirm glibc pam linux-api-headers make diffutils
          mkdir /libcap
          cd /libcap
          curl --output libcap.tar.gz --fail --location https://git.kernel.org/pub/scm/libs/libcap/libcap.git/snapshot/libcap-2.65.tar.gz
          echo "b0c770a99f978ca32ce58fb72b23d2a883b160aa30ee909fb83ba4003efc771c  libcap.tar.gz" > libcap.sha
          sha256sum -c libcap.sha
          tar -zxvf libcap.tar.gz
          cd libcap-2.65
          make
          make install

      - name: Set up Docker's Apt repository
        if: contains(matrix.container, 'ubuntu')
        # https://docs.docker.com/engine/install/ubuntu/
        run: |
          apt update
          apt --yes install ca-certificates curl gnupg
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          chmod a+r /etc/apt/keyrings/docker.gpg

          # Add the repository to Apt sources:
          echo \
            "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
            tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt update

      - name: Install dependencies with apt
        if: contains(matrix.container, 'ubuntu')
        # please make sure this is in sync with the README.md / installation docs
        run: |
          apt update
          apt --yes install git make cmake clang llvm lcov libcap-dev default-jdk maven curl unzip
          apt --yes install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Install gradle
        if: contains(matrix.container, 'ubuntu')
        run: |
          curl --fail --location https://services.gradle.org/distributions/gradle-7.5.1-bin.zip --output /tmp/gradle-7.5.1-bin.zip
          unzip -d /opt/gradle /tmp/gradle-7.5.1-bin.zip
          echo "/opt/gradle/gradle-7.5.1/bin" >> $GITHUB_PATH

      - name: Install bazel
        run: |
          curl -L https://github.com/bazelbuild/bazelisk/releases/download/v1.15.0/bazelisk-linux-amd64 -o /usr/bin/bazel
          chmod +x /usr/bin/bazel

      - uses: actions/checkout@v3

      - name: Install cifuzz
        run: make install

      - name: Run cifuzz examples
        uses: ./.github/actions/run_cifuzz
        with:
          os: ${{ matrix.container }}

  # In general it would be nice to use windows container for testing this,
  # but by now they are not available for windows based github runner
  from_source_mac-windows:
    name: ${{ matrix.os }} - install from source
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, windows-2022]
    steps:
      - uses: actions/checkout@v3

      - name: Setup VM for cifuzz
        uses: ./.github/actions/vm_setup
        with:
          os: ${{ matrix.os }}

      - name: Install cifuzz
        run: make install

      - name: Run cifuzz examples
        uses: ./.github/actions/run_cifuzz
        with:
          os: ${{ matrix.os }}
