# This Pipeline executes some kind of e2e test by checking if cifuzz can be build from source
#
# To not unnecessarily lengthen the runtime of the PR pipelines we just run these
# tests after pushing to main.
name: E2E Source Installation/Example Test

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  from_source:
    name: ${{ matrix.os }} - install from source
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, windows-2022, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3

      - name: Setup VM for cifuzz
        uses: ./.github/actions/vm_setup
        with:
          repository_user: ${{ secrets.REPOSITORY_USER }}
          repository_token: ${{ secrets.REPOSITORY_TOKEN }}
          os: ${{ matrix.os }}

      - name: Install cifuzz
        run: make install

      - name: Run cifuzz examples
        uses: ./.github/actions/run_cifuzz
        with:
          os: ${{ matrix.os }}
